src/BudgetAnalyzer/Models/BankAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BudgetAnalyzer.Models
{
    public class BankAccount
    {
        public BankAccount()
        {
            Operations = new List<AccountOperation>();
            CorrespondentOperations = new List<AccountOperation>();
        }

        public int Id { get; set; }

        public string UserId { get; set; }

        public virtual ApplicationUser User { get; set; }

        [Display(Name = "Bank")]
        public int? BankId { get; set; }

        public virtual Bank Bank { get; set; }

        public BankAccountType Type { get; set; }

        public string Name { get; set; }

        public virtual ICollection<AccountOperation> Operations { get; set; }

        public virtual ICollection<AccountOperation> CorrespondentOperations { get; set; }
    }
}

src/BudgetAnalyzer/Models/BankAccountType.cs
using System.ComponentModel.DataAnnotations;

namespace BudgetAnalyzer.Models
{
    public enum BankAccountType
    {
        [Display(Name = "-- Not specified --")]
        NotSpecified = 0,
        Deposit = 1,
        Credit = 2
    }
}

src/BudgetAnalyzer/ViewModels/BankAccounts/BankAccountDetailsTab.cs
namespace BudgetAnalyzer.ViewModels.BankAccounts
{
    public enum BankAccountDetailsTab
    {
        AccountOperations,
        UploadedStatements
    }
}

src/BudgetAnalyzer/ViewModels/BankAccounts/BankAccountDetailsViewModel.cs
using BudgetAnalyzer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BudgetAnalyzer.ViewModels.BankAccounts
{
    public class BankAccountDetailsViewModel
    {
        public BankAccountDetailsViewModel(BankAccount account, BankAccountDetailsTab activeTab, AccountStatement[] statements = null)
        {
            Account = account;
            ActiveTab = activeTab;
            Statements = statements;
        }

        public BankAccount Account { get; }

        public BankAccountDetailsTab ActiveTab { get; }

        public AccountStatement[] Statements { get; }
    }
}

src/BudgetAnalyzer/Controllers/AccountStatementsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using BudgetAnalyzer.Models;
using BudgetAnalyzer.ViewModels.AccountStatements;
using System;
using BudgetAnalyzer.Services;
using System.Diagnostics;

namespace BudgetAnalyzer.Controllers
{
    public class AccountStatementsController : Controller
    {
        private readonly ApplicationDbContext context;

        private readonly IBankAccountStatementProcessor statementProcessor;

        public AccountStatementsController(
            ApplicationDbContext context,
            IBankAccountStatementProcessor statementProcessor)
        {
            this.context = context;
            this.statementProcessor = statementProcessor;
        }

        // GET: AccountStatements
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = context.AccountStatements.Include(a => a.BankAccount).Include(a => a.FileUpload);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: AccountStatements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            AccountStatement accountStatement = await context.AccountStatements.SingleAsync(m => m.Id == id);
            if (accountStatement == null)
            {
                return HttpNotFound();
            }

            return View(accountStatement);
        }

        // GET: AccountStatements/Create
        public IActionResult Create(int? accountId = null)
        {
            var viewModel = new AccountStatementViewModel { BankAccountId = accountId };
            ViewData["BankAccountId"] = new SelectList(context.BankAccounts, "Id", "Name");
            return View(viewModel);
        }

        // POST: AccountStatements/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AccountStatementViewModel model)
        {
            if (ModelState.IsValid)
            {
                IFileUpload upload;
                try
                {
                    upload = await context.SaveFileUploadAsync(model.Attachment);
                }
                catch (Exception ex)
                {
                    throw new Exception("Failed to save uploaded file. Please upload it again later.", ex);
                }
                var statement = new AccountStatement
                {
                    BankAccountId = model.BankAccountId.Value,
                    FileUploadId = upload.Id,
                    ProcessedAt = DateTimeOffset.Now
                };
                context.AccountStatements.Add(statement);
                await context.SaveChangesAsync();

                statementProcessor.StartProcessing(statement.Id);

                return RedirectToAction("Index");
            }
            ViewData["BankAccountId"] = new SelectList(context.BankAccounts, "Id", "Name", model.BankAccountId);
            return View(model);
        }

        // GET: AccountStatements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            AccountStatement accountStatement = await context.AccountStatements.SingleAsync(m => m.Id == id);
            if (accountStatement == null)
            {
                return HttpNotFound();
            }
            ViewData["BankAccountId"] = new SelectList(context.BankAccounts, "Id", "BankAccount", accountStatement.BankAccountId);
            ViewData["FileUploadId"] = new SelectList(context.FileUploads, "Id", "FileUpload", accountStatement.FileUploadId);
            return View(accountStatement);
        }

        // POST: AccountStatements/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AccountStatement accountStatement)
        {
            if (ModelState.IsValid)
            {
                context.Update(accountStatement);
                await context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["BankAccountId"] = new SelectList(context.BankAccounts, "Id", "BankAccount", accountStatement.BankAccountId);
            ViewData["FileUploadId"] = new SelectList(context.FileUploads, "Id", "FileUpload", accountStatement.FileUploadId);
            return View(accountStatement);
        }

        // GET: AccountStatements/Delete/5
        [ActionName("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            AccountStatement accountStatement = await context.AccountStatements.SingleAsync(m => m.Id == id);
            if (accountStatement == null)
            {
                return HttpNotFound();
            }

            return View(accountStatement);
        }

        // POST: AccountStatements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            AccountStatement accountStatement = await context.AccountStatements.SingleAsync(m => m.Id == id);
            context.AccountStatements.Remove(accountStatement);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

src/BudgetAnalyzer/Controllers/BankAccountsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using BudgetAnalyzer.Models;
using Microsoft.AspNet.Authorization;
using BudgetAnalyzer.ViewModels.BankAccounts;
using System.Security.Claims;

namespace BudgetAnalyzer.Controllers
{
    [Authorize]
    public class BankAccountsController : Controller
    {
        private ApplicationDbContext _context;

        public BankAccountsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: BankAccounts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BankAccounts.Include(b => b.Bank).Include(b => b.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BankAccounts/Details/5
        public async Task<IActionResult> Details(int? id, BankAccountDetailsTab tab = BankAccountDetailsTab.AccountOperations)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var userId = User.GetUserId();
            BankAccount bankAccount = await _context.BankAccounts
                .Include(a => a.Operations)
                .SingleAsync(m => m.Id == id && m.UserId == userId);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }

            var statements = tab == BankAccountDetailsTab.UploadedStatements
                ? await _context.AccountStatements.Where(s => s.BankAccountId == bankAccount.Id).ToArrayAsync()
                : null;

            var viewModel = new BankAccountDetailsViewModel(bankAccount, tab, statements);

            return View(viewModel);
        }

        // GET: BankAccounts/Create
        public IActionResult Create()
        {
            ViewData["BankId"] = new SelectList(_context.Banks, "Id", "Name");
            return View();
        }

        // POST: BankAccounts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BankAccount bankAccount)
        {
            if (ModelState.IsValid)
            {
                _context.BankAccounts.Add(bankAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["BankId"] = new SelectList(_context.Banks, "Id", "Name", bankAccount.BankId);
            return View(bankAccount);
        }

        // GET: BankAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            BankAccount bankAccount = await _context.BankAccounts.SingleAsync(m => m.Id == id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            ViewData["BankId"] = new SelectList(_context.Banks, "Id", "Name", bankAccount.BankId);
            return View(bankAccount);
        }

        // POST: BankAccounts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BankAccount bankAccount)
        {
            if (ModelState.IsValid)
            {
                _context.Update(bankAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["BankId"] = new SelectList(_context.Banks, "Id", "Name", bankAccount.BankId);
            return View(bankAccount);
        }

        // GET: BankAccounts/Delete/5
        [ActionName("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            BankAccount bankAccount = await _context.BankAccounts.SingleAsync(m => m.Id == id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }

            return View(bankAccount);
        }

        // POST: BankAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            BankAccount bankAccount = await _context.BankAccounts.SingleAsync(m => m.Id == id);
            _context.BankAccounts.Remove(bankAccount);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

src/BudgetAnalyzer/Controllers/BanksController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using BudgetAnalyzer.Models;

namespace BudgetAnalyzer.Controllers
{
    public class BanksController : Controller
    {
        private ApplicationDbContext _context;

        public BanksController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Banks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Banks.ToListAsync());
        }

        // GET: Banks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Bank bank = await _context.Banks.SingleAsync(m => m.Id == id);
            if (bank == null)
            {
                return HttpNotFound();
            }

            return View(bank);
        }

        // GET: Banks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Banks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Bank bank)
        {
            if (ModelState.IsValid)
            {
                _context.Banks.Add(bank);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(bank);
        }

        // GET: Banks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Bank bank = await _context.Banks.SingleAsync(m => m.Id == id);
            if (bank == null)
            {
                return HttpNotFound();
            }
            return View(bank);
        }

        // POST: Banks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Bank bank)
        {
            if (ModelState.IsValid)
            {
                _context.Update(bank);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(bank);
        }

        // GET: Banks/Delete/5
        [ActionName("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Bank bank = await _context.Banks.SingleAsync(m => m.Id == id);
            if (bank == null)
            {
                return HttpNotFound();
            }

            return View(bank);
        }

        // POST: Banks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Bank bank = await _context.Banks.SingleAsync(m => m.Id == id);
            _context.Banks.Remove(bank);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

src/BudgetAnalyzer/Views/BankAccounts/Create.cshtml
@model BudgetAnalyzer.Models.BankAccount
@using System.Security.Claims

@{
    ViewData["Title"] = "Create Bank Account";
}

<h2>Create Bank Account</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Bank Account</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <input asp-for="UserId" type="hidden" value="@User.GetUserId()" />
        <div class="form-group">
            <label asp-for="BankId" class="col-md-2 control-label"></label>
            <div class="col-md-4">
                <select asp-for="BankId" asp-items="@(ViewData["BankId"] as SelectList)" class="form-control">
                    <option value="">-- Not specified --</option>
                </select>
            </div>
            <div class="col-md-6">
                <h4>No your bank in list? <a asp-controller="Banks" asp-action="Create">Create it</a>.</h4>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<BankAccountType>()" class="form-control"></select>
                <span asp-validation-for="Type" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/BudgetAnalyzer/Views/BankAccounts/Delete.cshtml
@model BudgetAnalyzer.Models.BankAccount

@{
    ViewData["Title"] = "Delete Bank Account";
}

<h2>Delete Bank Account</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bank Account</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/BudgetAnalyzer/Views/BankAccounts/Details.cshtml
@model BudgetAnalyzer.ViewModels.BankAccounts.BankAccountDetailsViewModel
@using BudgetAnalyzer.ViewModels.BankAccounts

@{
    ViewData["Title"] = "Bank Account Details";
}

<h2>Bank Account Details</h2>

<div>
    <h4>Bank Account</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Account.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Account.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Account.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Account.Type)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.Account.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p>

<hr />

<div>
    @{
        string operationsTabActive = Model.ActiveTab == BankAccountDetailsTab.AccountOperations ? "active" : "";
        string statementsTabActive = Model.ActiveTab == BankAccountDetailsTab.UploadedStatements ? "active" : "";
    }

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="@operationsTabActive">
            <a asp-route-tab="@BankAccountDetailsTab.AccountOperations" role="tab">Account Operations</a>
        </li>
        <li role="presentation" class="@statementsTabActive">
            <a asp-route-tab="@BankAccountDetailsTab.UploadedStatements" role="tab">Uploaded Statements</a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane @operationsTabActive" id="home">
            @if (Model.Account.Operations.Any())
            {
                <div class="row">
                    @{
                        var operations = Model.Account.Operations.OrderByDescending(o => o.Time);
                        var operationsGroups = operations.GroupBy(o => o.Time.Date);
                    }
                    <table class="table table-condensed table-striped">
                        <thead>
                            <tr>
                                <th>Time</th>
                                <th>Debit</th>
                                <th>Credit</th>
                                <th>Saldo</th>
                                <th>Category/Comment</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var g in operationsGroups)
                            {
                                <tr>
                                    <td colspan="100">
                                        <span>@g.Key.ToLongDateString()</span>
                                    </td>
                                </tr>
                                @foreach (var op in g)
                                {
                                    <tr>
                                        <td>@op.Time.ToShortTimeString()</td>
                                        <td>@(op.Ammount > 0 ? op.Ammount.ToString() : "")</td>
                                        <td>@(op.Ammount < 0 ? op.Ammount.ToString() : "")</td>
                                        <td>@op.Saldo</td>
                                        <td>@op.Name</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            }
            else
            {
                <p>
                    No operations yet. 
                    <a asp-controller="AccountStatements"
                       asp-action="Create"
                       asp-route-accountId="@Model.Account.Id">
                        Upload Bank Account Statement
                    </a>
                </p>
            }
        </div>
        <div role="tabpanel" class="tab-pane @statementsTabActive">
            @if (Model.Statements != null && Model.Statements.Any())
            {
                <a asp-controller="AccountStatements"
                   asp-action="Create"
                   asp-route-accountId="@Model.Account.Id">
                    Upload Bank Account Statement
                </a>
                @foreach (var s in Model.Statements)
                {
                    <span>#@s.Id</span>
                }
            }
            else
            {
                <p>No statements yet. 
                    <a asp-controller="AccountStatements" 
                       asp-action="Create" 
                       asp-route-accountId="@Model.Account.Id">
                        Upload Bank Account Statement
                    </a>
                </p>
            }
        </div>
    </div>

</div>

src/BudgetAnalyzer/Views/BankAccounts/Edit.cshtml
@model BudgetAnalyzer.Models.BankAccount
@using System.Security.Claims

@{
    ViewData["Title"] = "Edit Bank Account";
}

<h2>Edit Bank Account</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Bank Account</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="UserId" value="@User.GetUserId()" />
        <div class="form-group">
            <label asp-for="BankId" class="control-label col-md-2"></label>
            <div class="col-md-4">
                <select asp-for="BankId" asp-items="@(ViewData["BankId"] as SelectList)" class="form-control" >
                    <option value="">-- Not specified --</option>
                </select>
                <span asp-validation-for="BankId" class="text-danger" />
            </div>
            <div class="col-md-6">
                <h4>No your bank in list? <a asp-controller="Banks" asp-action="Create">Create it</a>.</h4>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<BankAccountType>()" class="form-control"></select>
                <span asp-validation-for="Type" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/BudgetAnalyzer/Views/BankAccounts/Index.cshtml
@model IEnumerable<BudgetAnalyzer.Models.BankAccount>

@{
    ViewData["Title"] = "Bank Accounts";
}

@if (Model.Any())
{
    <h2>Your Bank Accounts</h2>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </table>
}
else
{
    <div class="jumbotron">
        <h1>No bank accounts yet</h1>
        <p><a asp-action="Create">Create new</a> bank account</p>
    </div>
}